version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vit_results
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    
volumes:
  db_data: