version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agri-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: agri_shop
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    volumes:
      - db_data:/var/lib/mysql
      - ./web/src/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
    ports:
      - "3306:3306"

  web:
    build:
      context: ./web
      dockerfile: dockerfile
    container_name: agri_web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./web/src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: agri_shop
      DB_USER: shopuser
      DB_PASS: shoppass

volumes:
  db_data:
  